site_name: Disenone's Wiki
site_url: https://wiki.disenone.site
site_author: Disenone
site_description: 无止境
repo_url: https://github.com/disenone/wiki_blog
repo_name: GitHub
copyright: Copyright &copy; 2014 - 2024 by <a href="https://github.com/disenone"> Disenone </a>
edit_uri: edit/main/docs/ # 编辑按钮的url

theme:
  name: material
  custom_dir: overrides/
  language: zh
  font: #false # 国内网络访问 Google 源可能会有问题
    text: "Noto Sans SC - local"
    #code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)" # 检查用户系统配置是否为亮色
      scheme: default # 亮色模式
      primary: 4051b5 # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)" # 检查用户系统配置是否为暗色
      scheme: slate # 暗色模式
      primary: black # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye-outline
        name: 切换亮色模式
  logo: assets/favicon/android-chrome-512x512.png
  favicon: assets/favicon/favicon.ico
  features:
    - content.code.copy # 代码块复制按钮
    - content.code.annotate
    - content.code.select
    - content.action.edit # 文章编辑按钮
    - content.tooltips
    #- navigation.instant # Instant loading，像个单页应用
    - navigation.tracking # Anchor tracking
    - navigation.tabs # 导航栏
    - navigation.footer # 上一篇 / 下一篇导航按钮
    #- navigation.tabs.sticky # 导航栏不随页面滚动隐藏
    - navigation.sections # 侧边栏分组显示
    #- navigation.expand # 导航栏自动展开
    - navigation.indexes # 组标题有专属页面
    - toc.follow # 目录自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索推荐
    #- navigation.prune # 导航修剪，仅渲染可见链接，优化文档数量超过100的站点（实验），会导致页面间跳转速度变慢
    #- search.highlight
  icon:
    repo: material/github
    #edit: material/pencil

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: zh-Hant
          name: 繁體中文
          build: true
          nav_translations:
            Home: Home
            编程技术: 編程技術
            游戏开发: 遊戲開發
            基础: 基礎
        - locale: en
          name: English
          build: true
          nav_translations:
            Home: Home
            编程技术: Programming
            游戏开发: Game Dev
            基础: Basic
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Home
            编程技术: Tecnología de programación
            游戏开发: Desarrollo de juegos
            基础: Fundamentos
        - locale: ja
          name: 日本語
          build: true
          nav_translations:
            Home: Home
            编程技术: プログラミング技術
            游戏开发: ゲーム開発
            基础: 基礎
        - locale: de
          name: Deutsch
          build: true
          nav_translations:
            Home: Home
            编程技术: Programmiertechniken
            游戏开发: Spieleentwicklung
            基础: Grundlagen
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Home
            编程技术: Techniques de programmation
            游戏开发: Développement de jeux
            基础: Fondamentaux
        - locale: ar
          name: العربية
          build: true
          nav_translations:
            Home: Home
            编程技术: تقنيات البرمجة
            游戏开发: تطوير الألعاب
            基础: الأساسيات

  - search
  - macros
  - blog:
      post_readtime: true
      post_date_format: full
  - git-revision-date-localized:
      type: custom
      timezone: Asia/Shanghai
      enable_creation_date: true
      custom_format: "%Y-%m-%d"
      exclude:
        - zh/index.md
        - zh/contact-and-subscribe.md
        - en/index.md
        - en/contact-and-subscribe.md
        - es/index.md
        - es/contact-and-subscribe.md
        - ja/index.md
        - ja/contact-and-subscribe.md
        - de/index.md
        - de/contact-and-subscribe.md
        - fr/index.md
        - fr/contact-and-subscribe.md
        - ar/index.md
        - ar/contact-and-subscribe.md
        - zh-Hant/*.md
  - rss:
      abstract_chars_count: -1 # -1 for full content
      #categories:
      # - tags
      #comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        # as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 1000
      pretty_print: true
      match_path: "(zh|blog)/.*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - glightbox
  - mkdocs-video
  - exclude:
    glob:
      - asset/ext/*.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.snippets:
      base_path: ['.', 'docs/assets/ext']
      check_paths: true
      restrict_base_path: true
      auto_append: []
  - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji
       emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - admonition
  - tables
  - footnotes
  - def_list
  - abbr

extra_css:
  - assets/css/style.css

#############################################################
#############################################################
#############################################################

nav:
  - Home: index.md
  - 编程技术:
    - C/C++:
      - cpp-C和Cpp的命令行参数处理总结.md
      - cpp-C和Cpp宏编程解析.md
      - cpp-编写Windows下的MemoryLeakDetector.md
      - cpp-KCP源码剖析.md
    - Python:
      - py-使用VisualStudio2015编译Python2.7.11.md
      - py-Python杂谈1-探究__builtins__.md
      - py-Python杂谈2-Python312-热更新.md
  - 游戏开发:
    - 基础:
      - game-游戏AOI算法解析和性能实测.md
    - UE:
      - ue-使用FASTBuild编译UE4和UE5.md
      - ue-通过插件源码添加插件.md
      - ue-扩展编辑器菜单.md
      - ue-使用路径形式扩展菜单.md
      - ue-设置本地化多语言.md
      - ue-图片-各种图片操作.md
      - ue-编辑器插件-EditorPlus.md
      - ue-插件-AIChatPlus.md
    - Unity:
      - unity-Unity第三人称相机构建(上).md
      - unity-Unity第三人称相机构建(下).md
      - unity-Unity人物控制.md
      - unity-Unity画深度图和边缘检测.md
      - unity-Unity实现体积光照散射.md
